table d_cluster_selo
	lineageTag: 3c4d5e6f-7a8b-9c0d-1e2f-3a4b5c6d7e8f

	column 'Nome do Selo'
		dataType: string
		lineageTag: col-selo-nome
		summarizeBy: none
		sourceColumn: SEL_NOME

	column 'Perfil Alvo'
		dataType: string
		lineageTag: col-selo-perfil
		summarizeBy: none
		sourceColumn: PERFIL_ALVO

	column 'Critérios de Elegibilidade'
		dataType: string
		lineageTag: col-selo-criterios
		summarizeBy: none
		sourceColumn: CRITERIOS

	column 'Código da Cor Hex'
		dataType: string
		lineageTag: col-selo-cor
		summarizeBy: none
		sourceColumn: COR_HEX

	partition d_cluster_selo = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents("d:/Projetos/ProjectBI/5.JumpSantilana/data/gold/d_cluster_selo.csv"),[Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None]),
					#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"SEL_NOME", type text}, {"PERFIL_ALVO", type text}, {"CRITERIOS", type text}, {"COR_HEX", type text}})
				in
					#"Changed Type"

